# Generated by Django 4.2.7 on 2023-12-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theloner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='choicesClass',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='choices',
            name='realwolfClass',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='choices',
            name='timeoptionClass',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='choices',
            name='timeoptionText',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='secreturl',
            name='additionalCss',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='choices',
            name='headerClass',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='choices',
            name='headerCssUrl',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='choices',
            name='iconClass',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='choices',
            name='iconSrc',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='choices',
            name='tellstoryClass',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='choices',
            name='tellstoryText',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='choices',
            name='wolfClass',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
