# Generated by Django 4.2.7 on 2024-01-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theloner', '0002_choices_choicesclass_choices_realwolfclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='headerIsInternalLink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choices',
            name='iconIsInternalLink',
            field=models.BooleanField(default=False),
        ),
    ]
