# Generated by Django 4.2.7 on 2024-01-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theloner', '0003_choices_headerisinternallink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secreturl',
            name='cssIsInternalLink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='secreturl',
            name='additionalCss',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
