# Generated by Django 4.2.7 on 2024-01-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theloner', '0004_secreturl_cssisinternallink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='timeoptionAnimation',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
