# Generated by Django 4.2.7 on 2024-01-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theloner', '0005_choices_timeoptionanimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='bodyClass',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
