# Generated by Django 4.2.7 on 2024-01-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theloner', '0006_choices_bodyclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='belowTellstory',
            field=models.TextField(blank=True),
        ),
    ]
