# Generated by Django 4.2.7 on 2024-01-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theloner', '0007_choices_belowtellstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='belowTellstory',
        ),
        migrations.CreateModel(
            name='additionalPageHtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagType', models.CharField(choices=[('div', 'div'), ('pre', 'pre')], max_length=100)),
                ('tagClasses', models.CharField(blank=True, max_length=2000)),
                ('contentInside', models.TextField(blank=True)),
                ('insertedInto', models.ManyToManyField(to='theloner.secreturl')),
            ],
        ),
    ]
