# Generated by Django 4.2.7 on 2024-01-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theloner', '0008_remove_choices_belowtellstory_additionalpagehtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalpagehtml',
            name='insertBefore',
            field=models.IntegerField(choices=[(0, 'header'), (1, 'wolf'), (2, 'choices'), (3, 'tellstory'), (4, 'beyond')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionalpagehtml',
            name='tagType',
            field=models.CharField(choices=[('div', 'div'), ('pre', 'pre'), ('img', 'img'), ('pre', 'pre'), ('p', 'p'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6')], max_length=100),
        ),
    ]
