# Generated by Django 4.2.7 on 2024-01-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theloner', '0010_additionaloptionhtml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalpagehtml',
            old_name='insertedInto',
            new_name='pages_inserted',
        ),
    ]
